# Generated by Django 5.1.2 on 2024-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/wp7329095-minimal-mountain-wallpapers.jpg', upload_to='products/'),
        ),
    ]
