# Generated by Django 5.1.2 on 2024-11-29 15:14
from django.db import migrations


# Migration code for SQLite
class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_cart_created_at"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS decrease_stock_after_insert;
            DROP TRIGGER IF EXISTS decrease_stock_after_update;

            CREATE TRIGGER decrease_stock_after_insert
            AFTER INSERT ON base_cartitem
            BEGIN
                UPDATE base_product
                SET stock = stock - NEW.quantity
                WHERE id = NEW.product_id;
            END;

            CREATE TRIGGER decrease_stock_after_update
            AFTER UPDATE OF quantity ON base_cartitem
            BEGIN
                UPDATE base_product
                SET stock = stock - (NEW.quantity - OLD.quantity)
                WHERE id = NEW.product_id;
            END;
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS decrease_stock_after_insert;
                DROP TRIGGER IF EXISTS decrease_stock_after_update;
            """,
        ),
    ]
