# Generated by Django 5.1.2 on 2024-11-29 15:14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_auto_20241129_2114"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS increase_stock_after_delete;

            CREATE TRIGGER increase_stock_after_delete
            AFTER DELETE ON base_cartitem
            BEGIN
                UPDATE base_product
                SET stock = stock + OLD.quantity
                WHERE id = OLD.product_id;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS increase_stock_after_delete;",
        ),
    ]
